[package]
name = "metrics"
version = "0.1.0"
authors = ["S.Percentage"]
description = "Metrics Library(Point, Size, Rect...) with COMDrive"

[target."cfg(windows)".dependencies]
winapi = { git="https://github.com/retep998/winapi-rs", branch="dev", features=["d2d1"] }
